---
title: "class17"
format: pdf
---
```{r}
library(tximport)

# Identify quantification folders
folders <- list.dirs(path = ".", full.names = FALSE, recursive = FALSE)
folders <- folders[grepl("^SRR21568[0-9]+_quant$", folders)]

# Extract sample names from folder names
samples <- sub("_quant$", "", folders)

# Build file paths to abundance.h5 files
files <- file.path(folders, "abundance.h5")
names(files) <- samples

# Import Kallisto quantification data
txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)

```


```{r}
library(tximport)
```

```{r}
# setup the folder and filenames to read
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples
```

```{r}
txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)

```


```{r}
head(txi.kallisto$counts)
```

```{r}
colSums(txi.kallisto$counts)
sum(rowSums(txi.kallisto$counts)>0)
```

```{r}
#filter out no reads
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
```

```{r}
# filter out no change
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```

## PCA

```{r}
pca <- prcomp(t(x), scale=TRUE)

summary(pca)
```

```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)

```

Using ggplot instead, 

```{r}
library(ggplot2)
library(ggrepel)

# Make metadata object for the samples
colData <- data.frame(condition = factor(rep(c("control", "treatment"), each = 2)))
rownames(colData) <- colnames(txi.kallisto$counts)

# Make the data.frame for ggplot 
y <- as.data.frame(pca$x)
y$Condition <- as.factor(colData$condition)

ggplot(y) +
  aes(PC1, PC2, col=Condition) +
  geom_point() +
  geom_text_repel(label=rownames(y)) +
  theme_bw()

ggplot(y) +
  aes(PC1, PC3, col=Condition) +
  geom_point() +
  geom_text_repel(label=rownames(y)) +
  theme_bw()

ggplot(y) +
  aes(PC2, PC3, col=Condition) +
  geom_point() +
  geom_text_repel(label=rownames(y)) +
  theme_bw()
```

